package darcy.veterinary.infrastructure.sqlite

import darcy.veterinary.domain.model.InvoiceStatusHistory
import darcy.veterinary.infrastructure.database.DatabaseConnectionFactory

class SqliteInvoiceStatusHistoryRepository
